server:
  port: 70

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/peer
    username: root
    password: 123456

mybatis:
  configuration:
    jdbc-type-for-null: null
  mapper-locations: classpath:mapper/**/*.xml

logging:
  level:
    org.springframework: debug


