USE peer;

CREATE TABLE user_info (
	USER_NUM	INT(20)	PRIMARY KEY  AUTO_INCREMENT,
	USER_EMAIL	VARCHAR(30)	NOT NULL UNIQUE,
	USER_PASS	VARCHAR(30)	NOT NULL,
	USER_NAME	VARCHAR(20)	NOT NULL,
	USER_GENDER	VARCHAR(20)	NOT NULL,
	USER_AGE	INT(2)	NOT NULL,
	USER_PHONE	VARCHAR(20)	NOT NULL,
	USER_NICKNAME	VARCHAR(30)	NOT NULL,
    USER_REGE   datetime    NOT NULL,
	use_ny	INT(2) DEFAULT 1	NOT NULL,
	USER_AUTHORITY	INT(2)	DEFAULT 1    NOT NULL,
	USER_BIRTH DATE NOT NULL
	);
	
ALTER TABLE user_info ADD USER_EMAIL UNIQUE;
	
SELECT * FROM user_info;